### PR TITLE
Renaming gem

### PR DESCRIPTION
**Pull request by f19ps**
- Renaming gem to follow the standards described here https://guides.rubygems.org/name-your-gem/
- Now the gem can be used as `ActiveAdmin::AsyncExport`

### CODE REVIEW

**Review by fedeagripa — APPROVED** [review]

**Review by horacio — APPROVED** [review]

**Comment by santib** [comment]
@fpariani Why isn't this PR to `master` instead of a feature branch?

**Review by santiagovidal — APPROVED** [review]

**Comment by f19ps** [comment]
> @fpariani Why isn't this PR to `master` instead of a feature branch?

It was because it depends on the previous PR (linked to that branch). In this way, you can see only the changes related to this branch.

**Comment by santib** [comment]
> > @fpariani Why isn't this PR to `master` instead of a feature branch?
> 
> It was because it depends on the previous PR (linked to that branch). In this way, you can see only the changes related to this branch.

My question is: why does the rename of the gem depends on a feature? I don't think they are related at all

**Comment by f19ps** [comment]
> > > @fpariani Why isn't this PR to `master` instead of a feature branch?
> > 
> > 
> > It was because it depends on the previous PR (linked to that branch). In this way, you can see only the changes related to this branch.
> 
> My question is: why does the rename of the gem depends on a feature? I don't think they are related at all

Got it, I don't have a strong reason. I did it because there are some files that were manipulated in both PRs and I think this way allows me to merge in an easier way when the previous one has been merged.

**Comment by santib** [comment]
> > > > @fpariani Why isn't this PR to `master` instead of a feature branch?
> > > 
> > > 
> > > It was because it depends on the previous PR (linked to that branch). In this way, you can see only the changes related to this branch.
> > 
> > 
> > My question is: why does the rename of the gem depends on a feature? I don't think they are related at all
> 
> Got it, I don't have a strong reason. I did it because there are some files that were manipulated in both PRs and I think this way allows me to merge in an easier way when the previous one has been merged.

Ok, for the future I recommend you always try to avoid dependencies on other work. In this case for example, the changes won't get to master until the other branch is approved and merged. Anyways, approved good job 💯

**Review by santib — APPROVED** [review]

**Review by jpascual1994 — APPROVED** [review]

**Review by marlomajor — APPROVED** [review]

**Pull request merged**
