### PR TITLE
Add support for local storage

### PR DESCRIPTION
**Pull request by afmicc**
## Add support for local storage

* Create Storage Service: the purpose of that is creates the instance of the storage service according to the one configured in the initializer to support different cloud providers. 
  * Note: any idea about how to resolve this in another way is welcome
* Create Disk service: to save files locally and no depend on cloud service to development purposes.

### CODE REVIEW

**Review by santib — APPROVED** [review]
Wouldn't it make sense to use ActiveStorage?

**Review by brunvez — APPROVED** [review]
Nice

**Comment by f19ps** [comment]
> Wouldn't it make sense to use ActiveStorage?

@santib I think that makes sense! The only problem here would be the Rails versions allowed to use the gem since using ActiveStorage would limit us to support Rails 5.2+, right? Maybe we can follow this approach in next versions (? WDYT?

**Review by f19ps — APPROVED** [review]

**Comment by santib** [comment]
> > Wouldn't it make sense to use ActiveStorage?
> 
> @santib I think that makes sense! The only problem here would be the Rails versions allowed to use the gem since using ActiveStorage would limit us to support Rails 5.2+, right? Maybe we can follow this approach in next versions (? WDYT?

Sure, no worries. Just that this code reminded me to it 🙈

**Pull request merged**
